### ISSUE TITLE
Not Working in firmware 03.26.33 

### ISSUE THREAD

**Issue by AhmedRazaTester** [WhiteaglePT/node-anviz#3]
working fine in 02.6.61. 
please reply

**Comment by WhiteaglePT** [comment]
Hello Ahmed,

This is based on the anviz protocol TC_B Communications Protocol (2.1),

Not sure what device you're referring to regarding that firmware version.

If you didn't managed to make it work please state device and link to the firmware being used and I'll have a look.

Thanks
